import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Marquista",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section className="">{children}</section>;
}
